### ISSUE TITLE
please add more api such as user's like list

### ISSUE THREAD

**Issue by Levix0501** [ardasoyturk/cloudflare-worker-twitter#1]

**Comment by ardasoyturk** [comment]
I've just checked about [likes endpoint from Twitter API](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/get-favorites-list) and I'll try to add it to the worker this week. Thanks for your feature request!

**Comment by Levix0501** [comment]
thanks. Expect your update

**Comment by ardasoyturk** [comment]
@Melonvin I added a new endpoint for likes, 7798b82008b24e79caf91ead8e49d886db4daed8.

**Comment by Levix0501** [comment]
@ardasoyturk Thanks a lot.Another question is how can we use the pagination.Can we realize the paging funtion through V1.1 api?

**Comment by ardasoyturk** [comment]
As far as I know, it is a v2 feature. (https://developer.twitter.com/en/docs/twitter-api/pagination)

**Comment by Levix0501** [comment]
I get it. Thank you!
